=== AleksandrMya/c4proto/c4xml-base/src/main/xsd/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="messagename">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="messageHeader" type="messageHeader"/>
                <xs:element name="body" type="msgBody"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="messageHeader">
        <xs:sequence>
            <xs:element name="version" type="xs:string"/>
            <xs:element name="sender" type="xs:string"/>
            <xs:element name="receiver" type="xs:string"/>
            <xs:element name="created" type="xs:dateTime"/>
            <xs:element name="messageId" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="msgBody">
        <xs:choice>
            <xs:element name="vessel_visit" type="vessel_visit"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="vessel_visit">
        <xs:sequence>
            <xs:element name="action" type="xs:string"/>
            <xs:element name="action_date" type="xs:dateTime"/>
            <xs:element name="vessel_visit_syncid" type="xs:string"/>
            <xs:element name="vessel_syncid" type="xs:string"/>
            <xs:element name="state">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="EXP"/>
                        <xs:enumeration value="BERTH"/>
                        <xs:enumeration value="WORK"/>
                        <xs:enumeration value="PAUSE"/>
                        <xs:enumeration value="WRKD"/>
                        <xs:enumeration value="DPTR"/>
                        <xs:enumeration value="CLOSD"/>
                        <xs:enumeration value="NEXP"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="in_voyage_num" type="xs:string"/>
            <xs:element name="out_voyage_num" type="xs:string"/>
            <xs:element name="eta" type="xs:dateTime"/>
            <xs:element name="plan_process_start" type="xs:dateTime"/>
            <xs:element name="plan_process_finish" type="xs:dateTime"/>
            <xs:element name="ship_line_agent_syncid" type="xs:string"/>
            <xs:element name="ship_line_syncid" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== AleksandrMya/c4proto/c4xml-base/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<messagename xsi:noNamespaceSchemaLocation="file:///C:/Users/User/Desktop/Cone/C4PROTO/c4xml-base/schema.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <messageHeader>
        <version>1.0</version>
        <sender>TK</sender>
        <receiver>TOS</receiver>
        <created>2017-10-27T18:54:00</created>
        <messageId>NBFILE000091</messageId>
    </messageHeader>
    <body>
        <vessel_visit>
            <action>insert</action>
            <action_date>2017-04-04T00:00:00</action_date>
            <vessel_visit_syncid>12312323</vessel_visit_syncid>
            <vessel_syncid>VESSEL/799</vessel_syncid>
            <state>EXP</state>
            <in_voyage_num>SEA42</in_voyage_num>
            <out_voyage_num>SEA42</out_voyage_num>
            <eta>2016-09-05T11:03:45</eta>
            <plan_process_start>2016-09-05T11:03:45</plan_process_start>
            <plan_process_finish>2016-09-05T11:03:45</plan_process_finish>
            <ship_line_agent_syncid>533</ship_line_agent_syncid>
            <ship_line_syncid>STAKEHOLDER/532</ship_line_syncid>
        </vessel_visit>
    </body>
</messagename>
